name: QRFileTransfer
options:
  objectVersion: 70
  bundleIdPrefix: com.qrfiletransfer
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
targets:
  QRFileTransfer:
    type: application
    platform: iOS
    sources:
      - path: QRFileTransfer
        excludes:
          - Info.plist
    info:
      path: QRFileTransfer/Info.plist
      properties:
        UILaunchScreen: {}
        NSCameraUsageDescription: "Нужен доступ к камере для сканирования QR-кодов"
        NSPhotoLibraryAddUsageDescription: "Полученные фото и видео сохраняются в галерею"
        CFBundleDisplayName: QR Share
        CFBundleShortVersionString: "1.9.0"
        CFBundleVersion: "22"
        CFBundleAlternateIcons:
          frame-32:
            CFBundleIconFiles: [frame-32]
            UIPrerenderedIcon: true
          frame-33:
            CFBundleIconFiles: [frame-33]
            UIPrerenderedIcon: true
          frame-34:
            CFBundleIconFiles: [frame-34]
            UIPrerenderedIcon: true
          frame-35:
            CFBundleIconFiles: [frame-35]
            UIPrerenderedIcon: true
          frame-36:
            CFBundleIconFiles: [frame-36]
            UIPrerenderedIcon: true
          frame-37:
            CFBundleIconFiles: [frame-37]
            UIPrerenderedIcon: true
          frame-38:
            CFBundleIconFiles: [frame-38]
            UIPrerenderedIcon: true
          frame-39:
            CFBundleIconFiles: [frame-39]
            UIPrerenderedIcon: true
          frame-40:
            CFBundleIconFiles: [frame-40]
            UIPrerenderedIcon: true
          frame-41:
            CFBundleIconFiles: [frame-41]
            UIPrerenderedIcon: true
          frame-42:
            CFBundleIconFiles: [frame-42]
            UIPrerenderedIcon: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
schemes:
  QRFileTransfer:
    build:
      targets:
        QRFileTransfer: all
    run:
      config: Debug